### ISSUE TITLE
Link to Qt Linguist Manual

### ISSUE THREAD

**Issue by vigejolla** [sailfishos/sdk-user-manual#1]
The section "Using i18n in your project" leaves many questions unanswered, like "what are id based translations?". That information can be found in the help, in Qt Linguist Manual. A link to qthelp://org.qt-project.qtlinguist.562/qtlinguist/linguist-id-based-i18n.html could help.

**Comment by llewelld** [comment]
I tried to add this link as it was, but using the qthelp:// transport it doesn't appear in the HTML. I used a link to the Qt web pages instead (see #6). Is this okay?

**Comment by vigejolla** [comment]
link to the web page it is then. We can change it later if someone figures out a way to link to other help files.
