### ISSUE TITLE
Updating translation files

### ISSUE THREAD

**Issue by vigejolla** [sailfishos/sdk-user-manual#2]
The "Using i18n support in your project" mentions running qmake and make as the only way to update the translation files, for example when adding new languages. Sure, the translation files are generated during build, but it's really not necessary to build the whole project if you just want to add a new language or update the translation files. There could be a mention of using "Tools -> External -> Linguist -> Update translations (lupdate)" there.

**Comment by llewelld** [comment]
Thanks for this (I didn't realise it was possible to do it this way). I've added some text in to explain this point. See #6.

**Comment by llewelld** [comment]
This change has been merged in, so I'll close it, but please reoopen if you think the wording should be improved.
