### ISSUE TITLE
TRANSLATIONS example is broken

### ISSUE THREAD

**Issue by vigejolla** [sailfishos/sdk-user-manual#3]
In "Using i18n support in your project", the given TRANSLATIONS example line is broken. It contains closing brace, but there is no corresponding opening brace.

**Comment by llewelld** [comment]
Well noticed. I think an artefact converting from inline code to block code example. I've removed the extraneous brace. See #6.

**Comment by llewelld** [comment]
This change has been merged in, so closing.
