### ISSUE TITLE
empty line in custom property example

### ISSUE THREAD

**Issue by vigejolla** [sailfishos/sdk-user-manual#4]
There is an extra empty line in the third code example in Custom context properties page:
Object::connect(&timer, &QTimer::timeout, [&count, context](){
         count++;
         context->setContextProperty("count", count); // Update variable value
                                                      // once per second

     });

**Comment by llewelld** [comment]
Now removed, see #6.

**Comment by llewelld** [comment]
This change has been merged in, so closing.
