### ISSUE TITLE
Multiple statements in one line

### ISSUE THREAD

**Issue by vigejolla** [sailfishos/sdk-user-manual#5]
The fourth code example in the Custom context properties page contain the following snippet:

void setCount(int count) {
         if (m_count != count) { m_count = count; emit countChanged(); }
     }

Qt Coding Style forbids multiple statemens on one line, so this should be:

void setCount(int count)  {
    if (m_count != count) {
        m_count = count;
        emit countChanged();
    }
}

**Comment by vigejolla** [comment]
```
void setCount(int count) {
    if (m_count != count) {
        m_count = count;
        emit countChanged();
    }
}
```

**Comment by martyone** [comment]
or even better :)
```
void setCount(int count) {
    if (m_count == count)
        return;

    m_count = count;
    emit countChanged();
}
```

**Comment by llewelld** [comment]
Thanks for flagging this. I've made the change, see #6.

**Comment by llewelld** [comment]
This change has been merged in, so closing.
